services:
  - type: web
    name: true-ops
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.13
      - key: FLASK_ENV
        value: production

