"""add maintenance scheduling fields

Revision ID: f8380d888b29
Revises: 
Create Date: 2026-05-07 19:01:12.648543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8380d888b29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('scheduled_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_tickets', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('estimated_minutes')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('scheduled_date')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
